# HW 9 | Question 3

In [1]:
import numpy as np

In [11]:
# apply filter to image
def convolve2d(image, filter):
    filter_size = filter.shape[0]
    result_size = image.shape[0] - filter_size + 1
    result = np.zeros((result_size, result_size))

    for i in range(result_size):
        for j in range(result_size):
            result[i, j] = np.sum(image[i:i+filter_size, j:j+filter_size] * filter)

    return result

In [12]:
image = np.array(
    [[1, 1, 2, 3, 4, 2],
    [2, 5, 9, 7, 6, 5],
    [1, 2, 0, 1, 5, 4],
    [1, 2, 2, 1, 7, 0],
    [6, 4, 0, 1, 5, 2],
    [4, 3, 3, 2, 5, 1]]
)

In [15]:
# question 3

# horizontal edge
q_3a = np.array(
    [[-1, -1, -1],
    [1, 1, 1],
    [-1, -1, -1]]
) 

# vertical edge
q_3b = np.array(
    [[-1, 1, -1],
    [-1, 1, -1],
    [-1, 1, -1]]
) 

# horizontal edge
q_3c = np.array(
    [[1, -1, -1],
    [-1, 1, -1],
    [-1, -1, 1]]
) 

In [14]:
question_3a_array = convolve2d(image, q_3a)
question_3a_array


array([[  9.,  12.,   7.,  -1.],
       [-18., -23., -26., -16.],
       [ -8.,  -3.,  -2., -10.],
       [ -5.,  -8., -14.,  -8.]])

In [16]:
question_3b_array = convolve2d(image, q_3b)
question_3b_array


array([[ -7.,  -8., -15.,  -7.],
       [ -6.,  -7., -20.,   0.],
       [ -2.,  -9., -16.,   8.],
       [ -7.,  -8., -18.,  10.]])

In [17]:
question_3c_array = convolve2d(image, q_3c)
question_3c_array


array([[-11.,  -8.,  -9., -11.],
       [-12., -17.,  -4., -12.],
       [-12.,  -3., -10.,  -6.],
       [ -9., -10., -10., -10.]])